export const DOWNLOAD_ORDER = 'DOWNLOAD_ORDER';
export const DOWNLOAD_ORDER_SUCCESS = 'DOWNLOAD_ORDER_SUCCESS';
export const DOWNLOAD_ORDER_ERROR = 'DOWNLOAD_ORDER_ERROR';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';